import sys

D = {
'it': {
 'notif_title': 'LifeSync AI - Riepilogo della giornata',
 'notif_body': 'Apri l\'app per generare il riepilogo di oggi.',
 'ai_placeholder': 'Tocca il pulsante per generare il riepilogo di oggi con i tuoi passi e luoghi.',
 'backup_desc': 'I dati dei sensori e le posizioni restano sul dispositivo. Puoi esportarli in un file quando vuoi.',
 'export_error': 'Impossibile creare il file di backup. Riprova.',
 'act_still': 'Fermo', 'act_walking': 'Camminata', 'act_running': 'Corsa', 'act_driving': 'In veicolo', 'act_cycling': 'In bicicletta',
 'sum_header': 'Riepilogo di oggi',
 'sum_steps_line': 'Passi: %d', 'sum_places_line': 'Luoghi visitati: %d',
 'sum_above': 'Sei %d%% sopra la tua media degli ultimi giorni.',
 'sum_below': 'Sei %d%% sotto la tua media degli ultimi giorni.',
 'sum_same': 'In linea con la tua media degli ultimi giorni.',
 'sum_first': 'Continua così: la media si costruisce dopo qualche giorno di dati.',
 'sum_close_active': 'Ottima giornata di movimento!',
 'sum_close_light': 'Una giornata tranquilla: una passeggiata serale può aiutare.',
 'tab_today': 'Oggi', 'tab_history': 'Storico', 'tab_stats': 'Statistiche', 'tab_pro': 'Abbonamento',
 'history_title': 'Storico', 'history_empty': 'Ancora nessun giorno salvato. I tuoi dati appariranno qui.',
 'history_steps': '%d passi', 'history_places': '%d luoghi',
 'detail_summary': 'Riepilogo', 'detail_places': 'Luoghi', 'detail_no_summary': 'Nessun riepilogo generato per questo giorno.', 'detail_no_places': 'Nessun luogo registrato.',
 'stats_title': 'Statistiche', 'stats_last7': 'Passi negli ultimi 7 giorni', 'stats_average': 'Media passi', 'stats_total_places': 'Luoghi (7 giorni)', 'stats_best_day': 'Giorno migliore', 'stats_no_data': 'Servono alcuni giorni di dati per mostrare le statistiche.',
 'pro_status_active': 'Abbonamento attivo', 'pro_status_free': 'Versione gratuita',
 'pro_active_desc': 'Grazie! Hai riepiloghi illimitati e nessuna pubblicità.',
 'pro_free_desc': 'Nella versione gratuita il riepilogo si sblocca guardando un breve video.',
 'pro_manage': 'Gestisci abbonamento', 'pro_terms': 'Termini di utilizzo (EULA Apple)',
},
'en': {
 'notif_title': 'LifeSync AI - Daily summary',
 'notif_body': 'Open the app to generate today\'s summary.',
 'ai_placeholder': 'Tap the button to generate today\'s summary from your steps and places.',
 'backup_desc': 'Sensor data and locations stay on your device. You can export them to a file anytime.',
 'export_error': 'Could not create the backup file. Please try again.',
 'act_still': 'Still', 'act_walking': 'Walking', 'act_running': 'Running', 'act_driving': 'In vehicle', 'act_cycling': 'Cycling',
 'sum_header': 'Today\'s summary',
 'sum_steps_line': 'Steps: %d', 'sum_places_line': 'Places visited: %d',
 'sum_above': 'You are %d%% above your recent average.',
 'sum_below': 'You are %d%% below your recent average.',
 'sum_same': 'In line with your recent average.',
 'sum_first': 'Keep going: your average builds up after a few days of data.',
 'sum_close_active': 'Great day of movement!',
 'sum_close_light': 'A quiet day: an evening walk could help.',
 'tab_today': 'Today', 'tab_history': 'History', 'tab_stats': 'Stats', 'tab_pro': 'Subscription',
 'history_title': 'History', 'history_empty': 'No days saved yet. Your data will appear here.',
 'history_steps': '%d steps', 'history_places': '%d places',
 'detail_summary': 'Summary', 'detail_places': 'Places', 'detail_no_summary': 'No summary was generated for this day.', 'detail_no_places': 'No places recorded.',
 'stats_title': 'Stats', 'stats_last7': 'Steps in the last 7 days', 'stats_average': 'Average steps', 'stats_total_places': 'Places (7 days)', 'stats_best_day': 'Best day', 'stats_no_data': 'A few days of data are needed to show statistics.',
 'pro_status_active': 'Subscription active', 'pro_status_free': 'Free version',
 'pro_active_desc': 'Thank you! You have unlimited summaries and no ads.',
 'pro_free_desc': 'In the free version, the summary unlocks by watching a short video.',
 'pro_manage': 'Manage subscription', 'pro_terms': 'Terms of Use (Apple EULA)',
},
'es': {
 'notif_title': 'LifeSync AI - Resumen del día',
 'notif_body': 'Abre la app para generar el resumen de hoy.',
 'ai_placeholder': 'Toca el botón para generar el resumen de hoy con tus pasos y lugares.',
 'backup_desc': 'Los datos de sensores y ubicaciones permanecen en tu dispositivo. Puedes exportarlos a un archivo cuando quieras.',
 'export_error': 'No se pudo crear el archivo de copia. Inténtalo de nuevo.',
 'act_still': 'Quieto', 'act_walking': 'Caminando', 'act_running': 'Corriendo', 'act_driving': 'En vehículo', 'act_cycling': 'En bicicleta',
 'sum_header': 'Resumen de hoy',
 'sum_steps_line': 'Pasos: %d', 'sum_places_line': 'Lugares visitados: %d',
 'sum_above': 'Estás un %d%% por encima de tu media reciente.',
 'sum_below': 'Estás un %d%% por debajo de tu media reciente.',
 'sum_same': 'En línea con tu media reciente.',
 'sum_first': 'Sigue así: la media se construye tras unos días de datos.',
 'sum_close_active': '¡Gran día de movimiento!',
 'sum_close_light': 'Un día tranquilo: un paseo por la tarde puede ayudar.',
 'tab_today': 'Hoy', 'tab_history': 'Historial', 'tab_stats': 'Estadísticas', 'tab_pro': 'Suscripción',
 'history_title': 'Historial', 'history_empty': 'Aún no hay días guardados. Tus datos aparecerán aquí.',
 'history_steps': '%d pasos', 'history_places': '%d lugares',
 'detail_summary': 'Resumen', 'detail_places': 'Lugares', 'detail_no_summary': 'No se generó resumen para este día.', 'detail_no_places': 'No hay lugares registrados.',
 'stats_title': 'Estadísticas', 'stats_last7': 'Pasos en los últimos 7 días', 'stats_average': 'Media de pasos', 'stats_total_places': 'Lugares (7 días)', 'stats_best_day': 'Mejor día', 'stats_no_data': 'Se necesitan algunos días de datos para mostrar estadísticas.',
 'pro_status_active': 'Suscripción activa', 'pro_status_free': 'Versión gratuita',
 'pro_active_desc': '¡Gracias! Tienes resúmenes ilimitados y sin anuncios.',
 'pro_free_desc': 'En la versión gratuita el resumen se desbloquea viendo un vídeo corto.',
 'pro_manage': 'Gestionar suscripción', 'pro_terms': 'Términos de uso (EULA de Apple)',
},
'fr': {
 'notif_title': 'LifeSync AI - Résumé du jour',
 'notif_body': 'Ouvrez l\'app pour générer le résumé d\'aujourd\'hui.',
 'ai_placeholder': 'Touchez le bouton pour générer le résumé du jour avec vos pas et lieux.',
 'backup_desc': 'Les données des capteurs et les positions restent sur votre appareil. Vous pouvez les exporter dans un fichier à tout moment.',
 'export_error': 'Impossible de créer le fichier de sauvegarde. Réessayez.',
 'act_still': 'Immobile', 'act_walking': 'Marche', 'act_running': 'Course', 'act_driving': 'En véhicule', 'act_cycling': 'À vélo',
 'sum_header': 'Résumé du jour',
 'sum_steps_line': 'Pas : %d', 'sum_places_line': 'Lieux visités : %d',
 'sum_above': 'Vous êtes %d %% au-dessus de votre moyenne récente.',
 'sum_below': 'Vous êtes %d %% en dessous de votre moyenne récente.',
 'sum_same': 'Dans la lignée de votre moyenne récente.',
 'sum_first': 'Continuez : la moyenne se construit après quelques jours de données.',
 'sum_close_active': 'Belle journée de mouvement !',
 'sum_close_light': 'Une journée calme : une balade en soirée peut aider.',
 'tab_today': 'Aujourd\'hui', 'tab_history': 'Historique', 'tab_stats': 'Statistiques', 'tab_pro': 'Abonnement',
 'history_title': 'Historique', 'history_empty': 'Aucun jour enregistré pour l\'instant. Vos données apparaîtront ici.',
 'history_steps': '%d pas', 'history_places': '%d lieux',
 'detail_summary': 'Résumé', 'detail_places': 'Lieux', 'detail_no_summary': 'Aucun résumé généré pour ce jour.', 'detail_no_places': 'Aucun lieu enregistré.',
 'stats_title': 'Statistiques', 'stats_last7': 'Pas des 7 derniers jours', 'stats_average': 'Moyenne de pas', 'stats_total_places': 'Lieux (7 jours)', 'stats_best_day': 'Meilleur jour', 'stats_no_data': 'Quelques jours de données sont nécessaires pour afficher les statistiques.',
 'pro_status_active': 'Abonnement actif', 'pro_status_free': 'Version gratuite',
 'pro_active_desc': 'Merci ! Vous avez des résumés illimités et aucune publicité.',
 'pro_free_desc': 'Dans la version gratuite, le résumé se débloque en regardant une courte vidéo.',
 'pro_manage': 'Gérer l\'abonnement', 'pro_terms': 'Conditions d\'utilisation (EULA Apple)',
},
}

base = 'ios/LifeSyncAI/Resources/{}.lproj/Localizable.strings'
for lang, kv in D.items():
    path = base.format(lang)
    text = open(path, encoding='utf-8').read()
    existing = {line.split('"')[1] for line in text.splitlines() if line.startswith('"') and '" = ' in line}
    add = ''.join('"%s" = "%s";\n' % (k, v.replace('"', '\\"')) for k, v in kv.items() if k not in existing)
    if not text.endswith('\n'):
        text += '\n'
    open(path, 'w', encoding='utf-8').write(text + '\n' + add)
    print(lang, 'added', len([k for k in kv if k not in existing]))
